[project]
name = "santander-bank-share-value"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=26.5.1",
    "boto3>=1.43.66",
    "botocore>=1.43.66",
    "datetime>=6.0",
    "docker>=7.2.0",
    "dotenv>=0.9.9",
    "isort>=8.0.1",
    "pandas>=3.0.5",
    "pyarrow>=25.0.0",
    "yfinance>=1.5.2",
]
